src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentsRepository::class)]
class Comment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $comment_content = null;


    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    private ?Product $product = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    private ?User $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCommentContent(): ?string
    {
        return $this->comment_content;
    }

    public function setCommentContent(string $comment_content): static
    {
        $this->comment_content = $comment_content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): static
    {
        $this->product = $product;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }


}

src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\OneToMany(targetEntity: Comment::class, mappedBy: 'product')]
    private Collection $comments;

    #[ORM\OneToMany(targetEntity: Reservation::class, mappedBy: 'product')]
    private Collection $reservations;

    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'products')]
    private Collection $users;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column]
    private ?float $tva = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isHomepage = null;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->reservations = new ArrayCollection();
        $this->users = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setProduct($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getProduct() === $this) {
                $comment->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): static
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations->add($reservation);
            $reservation->setProduct($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): static
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getProduct() === $this) {
                $reservation->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->addProduct($this);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        if ($this->users->removeElement($user)) {
            $user->removeProduct($this);
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;

        return $this;
    }

    // fonction pour retourner le prix avec la tva
    public function getPriceWt()
    {
        $coeff = 1 + ($this->tva/100);

        return $coeff * $this->price;
    }

    public function getTva(): ?float
    {
        return $this->tva;
    }

    public function setTva(float $tva): static
    {
        $this->tva = $tva;

        return $this;
    }

    public function isIsHomepage(): ?bool
    {
        return $this->isHomepage;
    }

    public function setIsHomepage(?bool $isHomepage): static
    {
        $this->isHomepage = $isHomepage;

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Repository\CategoryRepository;
use App\Repository\ProductRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class ProductController extends AbstractController
{
    #[Route('/productlist')]
    public function productList (ProductRepository $productRepository)
    {
        $products = $productRepository->findAll();

        return $this->render('product/productList.html.twig', [
            'products' => $products
        ]);
    }

    #[Route('/productcategory/{slug}')]
    public function productCategory($slug, CategoryRepository $categoryRepository)
    {
        $category = $categoryRepository->findOneBy(['slug'=>$slug]);

        if(!$category){
            return $this->redirectToRoute('app_default_home');
        }

        return $this -> render('product/productCategory.html.twig',[
            'category' => $category
        ]);
    }

    #[Route('/productdetails/{slug}')]
    public function productDetails($slug, ProductRepository $productRepository)
    {
        $product = $productRepository->findOneBy(['slug'=>$slug]);

        if(!$product){
            return $this->redirectToRoute('app_default_home');
        }

        return $this -> render('product/productDetails.html.twig',[
            'product' => $product
        ]);
    }

}

templates/product/productCategory.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <h1 class="display-3 mb-5 text-center">{{ category.name }}</h1>

    <div class="container">
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for product in category.products %}
                <div class="col">
                    <div class="card h-100">
                        <div class="card-body">
                            <img src="/uploads/{{ product.image }}" alt="{{ product.name }}" class="img-fluid">
                            <h5 class="card-title text-center">{{ product.name }}</h5>
                            <div class="text-center">
                                {{ product.priceWt|price }}
                            </div>
                        </div>
                        <div class="card-footer">
                            <a href="{{ path('app_product_productdetails', {'slug': product.slug})}}" class="btn btn-dark w-100">Description</a>
                        </div>
                    </div>
                </div>
            {% else %}
                <div class="alert alert-danger">
                    Pas de produit pour le moment
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/product/productDetails.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <img src="/uploads/{{ product.image }}" alt="{{ product.name }}" class="img-fluid">
            </div>
            <div class="col-md-6">
                <small><i><a href="{{ path('app_product_productcategory', {slug : product.category.slug}) }}"  class="text-black">{{ product.category.name }}</a> > {{ product.name }}</i></small>
                <h1>{{ product.name }}</h1>
                <span class="d-block mb-3"> Prix : {{ product.pricewt|price }}</span>
                <p>{{ product.description | raw }}</p>
                <div class="mt-3">
                    <a href="{{ path('app_cart_add', {id : product.id}) }}" class="btn btn-dark">Ajouter au Panier</a>
                    <a href="{{ path('app_comment_add', {slug : product.slug}) }}" class="btn btn-dark">Ajouter un commentaire</a>
                    {% if app.user %}
                        {% if product in app.user.products %}
                            <a href="{{ path('app_user_removefavorite', {id: product.id}) }}" class="btn btn-dark">Supprimer des favoris</a>
                        {% else %}
                            <a class="btn btn-dark" href="{{ path('app_user_addfavorite', {id : product.id}) }}">Ajouter aux favoris</a>
                        {% endif %}
                    {% else %}
                        <a class="btn btn-dark" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">Ajouter aux favoris</a>
                    {% endif %}
                    <div class="collapse" id="collapseExample">
                        <div class="small">
                            Pour ajouter ce produit à vos favoris, <a href="{{ path('app_login') }}">connectez-vous</a> ou <a href="{{ path('app_register') }}">inscrivez-vous</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col">
                <h2>Commentaires</h2>
                {% if product.comments is empty %}
                    <p>Aucun commentaire pour le moment.</p>
                {% else %}
                    <ul class="list-group">
                        {% for comment in product.comments %}
                            <li class="list-group-item">
                                <strong>{{ comment.user.firstname }}</strong> : <br/>
                                {{ comment.commentContent|html }} <br/>
                                Le : {{ comment.createdAt|date('d/m/Y H:i') }}
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/product/productList.html.twig
{% extends 'base.html.twig'%}

{% block body %}

    <h1 class="text-center">Tous les produits</h1>

    <div class="container">
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for product in products %}
                <div class="col">
                    <div class="card h-100 shadow-lg">
                        <img src="/uploads/{{ product.image }}" class="card-img-top img-fluid" alt="{{ product.name }}">
                        <div class="card-body">
                            <h5 class="card-title text-center">{{ product.name }}</h5>
                            <div class="text-center">
                                {{ product.priceWt|price }}
                            </div>
                        </div>
                        <div class="card-footer">
                            <a href="{{ path('app_product_productdetails',{'slug': product.slug})}}" class="btn btn-dark w-100">Description</a>
                        </div>
                    </div>
                </div>
            {% else %}
                <div class="alert alert-danger">
                    Pas de produit pour le moment
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}