src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentsRepository::class)]
class Comment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $comment_content = null;


    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    private ?Product $product = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    private ?User $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCommentContent(): ?string
    {
        return $this->comment_content;
    }

    public function setCommentContent(string $comment_content): static
    {
        $this->comment_content = $comment_content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): static
    {
        $this->product = $product;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }


}

src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
class Order
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $addressDelivery = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    private ?User $user = null;

    // cascade: ['persist'] => permet de manipuler l'objet orderContent lorsqu'il est question de persister les données
    #[ORM\OneToMany(targetEntity: OrderContent::class, mappedBy: 'myOrder', cascade: ['persist'])]
    private Collection $orderContents;

    /*
     * état de la commande :
     * 1: en attente de paiement
     * 2: paiement validé
     * 3: commande expédiée
     */
    #[ORM\Column]
    private ?int $state = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $stripe_session_id = null;

    public function __construct()
    {
        $this->orderContents = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAddressDelivery(): ?string
    {
        return $this->addressDelivery;
    }

    public function setAddressDelivery(string $addressDelivery): static
    {
        $this->addressDelivery = $addressDelivery;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, OrderContent>
     */
    public function getOrderContents(): Collection
    {
        return $this->orderContents;
    }

    public function addOrderContent(OrderContent $orderContent): static
    {
        if (!$this->orderContents->contains($orderContent)) {
            $this->orderContents->add($orderContent);
            $orderContent->setMyOrder($this);
        }

        return $this;
    }

    public function removeOrderContent(OrderContent $orderContent): static
    {
        if ($this->orderContents->removeElement($orderContent)) {
            // set the owning side to null (unless already changed)
            if ($orderContent->getMyOrder() === $this) {
                $orderContent->setMyOrder(null);
            }
        }

        return $this;
    }

    public function getState(): ?int
    {
        return $this->state;
    }

    public function setState(int $state): static
    {
        $this->state = $state;

        return $this;
    }

    //fonctions permettant d'obtenir le prix total ttc et le prix de la tva de la commande afin d'afficher les résultats sur easyadmin
    public function getTotalTva()
    {
        $totalTva =0;
        $products = $this->getOrderContents();

        foreach ($products as $product){
            $coeff = $product->getProductTva() / 100;
            $totalTva += $product->getProductPrice() * $coeff;
        }

        return number_format($totalTva, 2);
    }

    public function getTotalWt()
    {
        $totalTtc =0;
        $products = $this->getOrderContents();

        foreach ($products as $product){
            $coeff = 1+ ($product->getProductTva() / 100);
            $totalTtc += ($product->getProductPrice() * $coeff) * $product->getProductQuantity();
        }

        return number_format($totalTtc, 2);
    }

    public function getStripeSessionId(): ?string
    {
        return $this->stripe_session_id;
    }

    public function setStripeSessionId(?string $stripe_session_id): static
    {
        $this->stripe_session_id = $stripe_session_id;

        return $this;
    }

}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Classe\Cart;
use App\Classe\Mail;
use App\Entity\Address;
use App\Entity\User;
use App\Form\AddressUserType;
use App\Form\PasswordUserType;
use App\Form\UserType;
use App\Repository\AddressRepository;
use App\Repository\CommentsRepository;
use App\Repository\OrderRepository;
use App\Repository\ProductRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;

class UserController extends AbstractController
{
    #[Route('/user/profile')]
    public function userProfile ()
    {
        // Récupérer l'utilisateur connecté à partir du token de sécurité
        $user = $this->getUser();


        // Vérifier si l'utilisateur est connecté
        if (!$user) {
            throw $this->createNotFoundException('Utilisateur non connecté');
        }

        // Vous pouvez maintenant passer l'utilisateur à votre template Twig pour l'affichage
        return $this->render('user/userProfile.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route ('user/modifier-mot-de-passe')]
    public function password(Request $request, UserPasswordHasherInterface $passwordHasher, EntityManagerInterface $entityManager)
    {

        // Récupérer l'utilisateur connecté à partir du token de sécurité
        $user = $this->getUser();

        //on créé le form et on lui envoie les infos de l'user et le passwordhasher pour comparer les mdp
        $form = $this->createForm(PasswordUserType::class, $user, [
            'passwordHasher' => $passwordHasher
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){
            $this->addFlash(
                'success',
                'Votre mot de passe est mis à jour'
            );

            $entityManager->flush(); //pas besoin de persist() car maj
        }

        return $this->render('user/changepwd.html.twig', [
            'modifyPwd'=> $form->createView()
        ]);
    }


    #[Route('/inscription', name: 'app_register')]
    public function userRegister (Request $request,UserPasswordHasherInterface $hasher ,EntityManagerInterface $manager)
    {
        #Creation d'un User vide
        $user = new User();
        $user->setCreatedAt(new \DateTimeImmutable());
        $user->setUpdatedAt(new \DateTimeImmutable());
        #Création du formulaire
        $form = $this->createForm(UserType::class, $user);

        #passer la requête au formulaire pour traitement
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){

            #Sauvegarder dans la BDD
            $manager->persist($user); #persist = enregistrer / dire au manager d'enregistrer dans la bdd
            $manager->flush(); #flush équivalent d'execute / requete Insert

            #Notification
            $this->addFlash('success','Félicitations, vous pouvez vous connecter.');

            #Envoi d'un email de confirmation d'inscription
            $mail = new Mail();
            $vars = [
                'firstname' => $user->getFirstName()
            ];
            $mail->send($user->getEmail(),$user->getFirstName().' '.$user->getFirstName(),'Bienvenue sur OnlyInAmerica','welcome.html', $vars);

            #Redirection page d'accueil
            return $this->redirectToRoute('app_login');

        }

        #Passage du formulaire à la vue
        return $this -> render('user/userRegister.html.twig', [
            'registerForm'=>$form
        ]);
    }

    #[Route('/user/addresses', name: 'app_user_addresses')]
    public function addresses()
    {
        return $this -> render('user/addresses.html.twig');
    }

    #[Route('/user/address/delete/{id}', name: 'app_user_address_delete')]
    public function addressDelete($id, AddressRepository $addressRepository, EntityManagerInterface $entityManager)
    {
        //Même principe pour le changement d'adresse, on vient récuperer l'adresse avec l'id et on check si elle existe et si elle correspond à l'user
        $address = $addressRepository->findOneById($id);
        if(!$address OR $address->getUser() != $this->getUser()){
            return $this->redirectToRoute('app_user_addresses');
        }
        $this->addFlash(
            'success',
            'Votre adresse a bien été supprimée.'
        );

        $entityManager->remove($address);
        $entityManager->flush();

        return $this->redirectToRoute('app_user_addresses');
    }


    //Utilisation de la même route pour ajouter ou modifier une adresse
    //Pour cela, on va passer en argument un id optionnel et on le met dans defaults (du tableau Route) à null
    //Si l'id existe on execute un traitement, sinon on créé un nouvel objet address
    #[Route('/user/address/add/{id}', name: 'app_user_address_form', defaults: ['id'=> null ])]
    public function addressForm(Request $request, EntityManagerInterface $entityManager, $id, AddressRepository $addressRepository, Cart $cart)
    {
        if($id){
            $address = $addressRepository->findOneById($id);
            // Sécurisation du changement d'adresse => est ce que l'adresse appartient à l'user en cours et si elle existe bien
            if(!$address OR $address->getUser() != $this->getUser()){
                return $this->redirectToRoute('app_user_addresses');
            }
        }else{
            $address = new Address();
            $address->setUser($this->getUser());
        }


        $form = $this->createForm(AddressUserType::class, $address);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $entityManager->persist($address);
            $entityManager->flush();

            $this->addFlash(
                'success',
                'Votre adresse est sauvegardée.'
            );

            // permet de revenir sur la page app_order si le panier contient des éléments
            if($cart->fullQuantity() > 0){
                return $this->redirectToRoute('app_order');
            }

            // si le panier est vide on retourne sur la page de profil/adresses
            return $this->redirectToRoute('app_user_addresses');
        }

        return $this -> render('user/addressForm.html.twig', [
            'adressForm' => $form
        ]);
    }


    #[Route('/user/favorite')]
    public function userFavorite ()
    {
        return $this -> render('user/userFavorite.html.twig');
    }
    #[Route('/user/favorite/add/{id}' , name: 'app_user_addfavorite')]
    public function addFavorite($id, ProductRepository $productRepository, EntityManagerInterface $entityManager, Request $request)
    {
        //1. récuperer l'objet du produit souhaité
        $product = $productRepository->findOneById($id);

        //2. si produit existant, ajouter le produit aux favoris
        if($product){
            $this->getUser()->addProduct($product);
            //3. sauvergarder en bdd
            $entityManager->flush();
        }

        $this->addFlash('success','Produit ajouté à vos favoris');

        //redirection vers la dernière url visitée
        return $this->redirect($request->headers->get('referer'));

    }
    #[Route('/user/favorite/remove/{id}' , name: 'app_user_removefavorite')]
    public function removeFavorite($id, ProductRepository $productRepository, EntityManagerInterface $entityManager, Request $request)
    {
        //1. récuperer l'objet du produit à supprimer
        $product = $productRepository->findOneById($id);

        //2. si produit existant, supprimer le produit aux favoris
        if($product){
            $this->addFlash('success','Produit supprimé de vos favoris');

            $this->getUser()->removeProduct($product);
            //3. sauvergarder en bdd
            $entityManager->flush();
        }else{
            $this->addFlash('danger','Produit introuvable');
        }

        return $this->redirect($request->headers->get('referer'));
    }
    #[Route('/user/comment', name: 'app_user_comment')]
    public function userComment(CommentsRepository $commentsRepository)
    {
        $user = $this->getUser();
        $comments = $commentsRepository->findBy(['user'=>$user]);


        return $this->render('user/userComment.html.twig',[
            'user' => $user,
            'comments' => $comments
        ]);
    }
    #[Route('/user/order', name: 'app_user_order')]
    public function userOrder(OrderRepository $orderRepository)
    {
        $orders = $orderRepository->findBy([
           'user' => $this->getUser(),
            'state' => [2, 3] //pour rechercher les commandes dont le state est supérieur à 1
        ]);

        return $this->render('user/userOrders.html.twig', [
            'orders' => $orders
        ]);
    }

    #[Route('/user/ordercontent/{id_order}', name: 'app_user_ordercontent')]
    public function userOrderContent($id_order, OrderRepository $orderRepository)
    {
        $order = $orderRepository->findOneBy([
            'id' => $id_order,
            'user' => $this->getUser()
        ]);

        if(!$order){
            return $this->redirectToRoute('app_default_home');
        }

        return $this->render('user/userOrderContent.html.twig', [
            'order' => $order
        ]);
    }
}

templates/user/addressForm.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une adresse{% endblock %}

{% block body %}

    <div class="container my-5">
        <h1 class="p-2">Mon Profil Utilisateur</h1>
        <div class="row">
            <div class="col-md-3">
                {% include '/components/_menuProfil.html.twig' %}
            </div>
            <div class="col-md-9">
                <h5>Mes adresses</h5>
                {{ form_start(adressForm) }}
                <div class="row">
                    <div class="col-md-6">{{ form_row(adressForm.firstname) }}</div>
                    <div class="col-md-6">{{ form_row(adressForm.lastname) }}</div>
                    <div class="col-md-6">{{ form_row(adressForm.address) }}</div>
                    <div class="col-md-6">{{ form_row(adressForm.zipcode) }}</div>
                    <div class="col-md-6">{{ form_row(adressForm.city) }}</div>
                    <div class="col-md-6">{{ form_row(adressForm.country) }}</div>
                    <div class="col-md-6">{{ form_row(adressForm.phone) }}</div>
                </div>
                {{ form_end(adressForm) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/user/addresses.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifiez votre mot de passe{% endblock %}

{% block body %}

    <div class="container my-5">
        <h1 class="p-2">Mon Profil Utilisateur</h1>

        <div class="row">
            <div class="col-md-3">
                {% include '/components/_menuProfil.html.twig' %}
            </div>
            <div class="col-md-9">
                <div class="d-flex justify-content-between">
                    <h5>Mes adresses</h5>
                    <a href="{{ path('app_user_address_form') }}" class="btn btn-dark">Ajouter une adresse</a>
                </div>

                {% if app.user.addresses|length == 0 %}
                    <p>Vous n'avez pas encore enregistré d'adresse sur votre compte OnlyInAmerica</p>
                {% else %}
                    <div class="row">
                        {% for address in app.user.addresses %}
                            <div class="col-md-4 mt-2">
                                <div class="bg-light p-2 text-center">
                                    <strong>{{ address.firstname }} {{ address.lastname }}</strong><br />
                                    {{ address.address }}<br />
                                    {{ address.zipcode }} {{ address.city }}<br />
                                    {{ address.country }}<br />
                                    Téléphone : {{ address.phone }}<br />
                                    <a href="{{ path('app_user_address_form', { id : address.id })}}" class="text-secondary small">Modifier</a><br />
                                    <a href="{{ path('app_user_address_delete', { id : address.id })}}" class="text-danger small">Supprimer</a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/user/changepwd.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifiez votre mot de passe{% endblock %}

{% block body %}

    <div class="container my-5">
        <h1 class="p-2">Mon Profil Utilisateur</h1>
        <div class="row">
            <div class="col-md-3">
                {% include '/components/_menuProfil.html.twig' %}
            </div>
            <div class="col-md-9">
                <h5>Modification de mon mot de passe</h5>
                {{ form(modifyPwd) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/user/userComment.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes favoris{% endblock %}

{% block body %}

    <div class="container my-5">
        <h1 class="p-2">Mon Profil Utilisateur</h1>
        <div class="row">
            <div class="col-md-3">
                {% include '/components/_menuProfil.html.twig' %}
            </div>
            <div class="col-md-9">
                <h5>Mes Commentaires</h5>
                {% if comments|length > 0 %}
                    <div class="row">
                        {% for comment in comments %}
                            Produit : {{ comment.product.name }} / Date : {{ comment.createdAt|date('d/m/Y H:i') }}
                            <div class="card mb-3">
                                <div class="card-body">
                                    <strong>Mon commentaire :</strong>
                                    <p class="card-text">{{ comment.commentContent|html }}</p>
                                    <div class="d-flex justify-content-end">
                                        <a href="{{ path('app_comment_delete',{id: comment.id}) }}" class="btn btn-danger m-1">Supprimer</a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    Vous n'avez pas de commentaires.
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/user/userFavorite.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes favoris{% endblock %}

{% block body %}

    <div class="container my-5">
        <h1 class="p-2">Mon Profil Utilisateur</h1>
        <div class="row">
            <div class="col-md-3">
                {% include '/components/_menuProfil.html.twig' %}
            </div>
            <div class="col-md-9">
                <h5>Mes favoris</h5>
                {% if app.user.products|length > 0 %}
                    <div class="row">
                        {% for product in app.user.products %}
                            <div class="col-md-3">
                                <img src="/uploads/{{ product.image }}" class="card-img-top img-fluid" alt="{{ product.name }}">
                                <h5 class="text-center">{{ product.name }}</h5>
                                <div class="text-center">
                                    <div>{{ product.price|price }}</div>
                                    <a href="{{ path('app_product_productdetails', {'slug': product.slug}) }}" class="btn btn-dark mt-2">Description</a>
                                </div>
                                <div class="text-center mt-2">
                                    <a href="{{ path('app_user_removefavorite', { id : product.id} ) }}" class="small text-danger">Supprimer</a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    Vous n'avez pas de produits dans vos favoris.
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/user/userOrderContent.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes Commandes{% endblock %}

{% block body %}

    <div class="container my-5">
        <h1 class="p-2">Mon Profil Utilisateur</h1>
        <div class="row">
            <div class="col-md-3">
                {% include '/components/_menuProfil.html.twig' %}
            </div>
            <div class="col-md-9">
                <h5>Ma commande n°{{ order.id }}</h5>
                <span>Date de la commande : {{ order.createdAt|date('d/m/y') }}</span><br />
                {# Nous allons chercher le template state afin d'afficher le statut de la commande et si il y a de nouveaux status qui sont ajoutés plus simple #}
                {# On procede à un include pour le template et on passe la variable field à qui on attribut un tableau avec la clé 'value' #}
                <span>{% include 'admin/state.html.twig' with { field : {'value' : order.state} } %}</span><br />
                <hr>

                <div class="my-4">
                    <strong>Adresse de livraison</strong><br />
                    {{ order.addressDelivery|raw }}
                </div>
                <hr>

                <strong>Contenu de la commande</strong><br />
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th scope="col">Image</th>
                        <th scope="col">Nom du produit</th>
                        <th scope="col">Quantité</th>
                        <th scope="col">Prix unitaire H.T</th>
                        <th scope="col">TVA</th>
                        <th scope="col">Prix T.T.C</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for product in order.orderContents %}
                        {# {{ dump(product) }} #}
                        <tr>
                            <td><img src="/uploads/{{product.productImage}}" width="100px" alt="{{ product.productName }}" ></td>
                            <td>{{ product.productName }}</td>
                            <td>{{ product.productQuantity }}</td>
                            <td>{{ product.productPrice|price }}</td>
                            <td>{{ product.productTva }}%</td>
                            {% set coeff = 1 + (product.productTva / 100) %} {# permet de déclarer une variable directement dans twig #}
                            <td>{{ ((coeff * product.productPrice) * product.productQuantity)|price }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div class="fs-5">
                    <strong>Total H.T : </strong> {{ (order.totalWt - order.totalTva )|price }}<br/>
                    <strong>Total TVA : </strong> {{ order.totalTva|price }}<br/>
                    <strong>Total T.T.C : </strong> {{ order.totalWt|price }}
                </div>
                <a href="{{ path('app_user_order') }}" class="btn btn-dark mt-4">Retour</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/userOrders.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes Commandes{% endblock %}

{% block body %}

    <div class="container my-5">
        <h1 class="p-2">Mon Profil Utilisateur</h1>
        <div class="row">
            <div class="col-md-3">
                {% include '/components/_menuProfil.html.twig' %}
            </div>
            <div class="col-md-9">
                <h5>Mes dernières commandes</h5>
                {% if orders|length == 0 %}
                    <div class="alert alert-info">
                        Vous n'avez pas encore passé de commande pour le moment.
                    </div>
                {% else %}
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th scope="col">N°</th>
                        <th scope="col">Date</th>
                        <th scope="col">Statut</th>
                        <th scope="col">Total T.T.C</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order in orders %}
                        <tr>
                            <td>{{ order.id }}</td>
                            <td>{{ order.createdAt|date('d/m/Y') }}</td>
                            <td>{% include 'admin/state.html.twig' with { field : {'value' : order.state} } %}</td>
                            <td>{{ order.totalWt|price }}</td>
                            <td><a href="{{ path('app_user_ordercontent', {'id_order' : order.id}) }}">Voir</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/user/userProfile.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon Profil Utilisateur{% endblock %}

{% block body %}
    <div class="container my-5">
        <h1 class="p-2">Mon Profil Utilisateur</h1>
        <div class="row">
            <div class="col-md-3">
                {% include '/components/_menuProfil.html.twig' %}
            </div>
            <div class="col-md-9">
                <h3>Bienvenue sur votre profil</h3>
                <p>Vous pouvez accéder ici à vos commandes, vos produits favoris, vos commentaires, vos adresses et même modifiez votre mot de passe !</p>
                <p>N'hésitez pas à nous contactez si vous avez le moindre problème : <a href="{{ path('app_contact') }}" class="small">Nous contactez</a></p>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/userRegister.html.twig
{% extends "base.html.twig" %}

{% block title %}Inscription{% endblock %}

{% block body %}
    <div class="container my-3">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <h1 class="text-center">Créer votre compte</h1>
                <div>
                    {{ form(registerForm) }}
                </div>
                Vous avez déjà un compte ? <a href="{{ path('app_login') }}">Connectez-vous</a>
            </div>

        </div>
    </div>
{% endblock %}